In [177]:
# 데이터 구성:Series, DataFrame
import pandas as pd
import numpy as np
# 데이터 시각화
import matplotlib.pyplot as plt
import matplotlib
# export_graphviz: 나무 구조 생성 및 저장 
from sklearn.tree import export_graphviz
# graphviz : 나무 구조 시각화  (.dot 확장자 파일 불러오기 등)
import graphviz
from sklearn.preprocessing import StandardScaler
# 데이터 분할:train, test
# 데이터 분할:train, test
from sklearn.model_selection import train_test_split
#분류 Random Forest
from sklearn.ensemble import RandomForestClassifier
# 최적 모델, 파라미터 탐색
from sklearn.model_selection import GridSearchCV

# 분류모델 평가 함수
from sklearn.metrics import accuracy_score, f1_score 
from sklearn.metrics import confusion_matrix, classification_report

In [178]:
sales = pd.read_csv("B1_유통(BtoB)/01_sales_data.csv")
customer = pd.read_csv("B1_유통(BtoB)/02_customer_data.csv")
stock = pd.read_csv("B1_유통(BtoB)/03_stock_data.csv")
df = pd.read_csv("k_customer.csv")
cs = pd.read_csv("category_sales.csv")

In [179]:
df

,Unnamed: 0,customer_id,min_basket,avg_basket,max_basket,tot_basket,num_basket,num_invoice,first_buy,last_buy,tot_sales,k_value
0,0,E12747,1,12.714286,48,979,24,8,582,261,3177.01,3
1,1,E12748,1,4.737705,48,10982,281,128,597,259,16546.71,2
2,2,E12749,1,7.421687,48,1232,57,4,472,262,3486.79,3
3,3,E12820,4,12.918919,48,478,17,3,585,262,598.58,1
4,4,E12821,2,11.666667,24,70,4,1,473,473,92.72,1
...,...,...,...,...,...,...,...,...,...,...,...,...
3347,3347,E18280,2,4.500000,8,45,9,1,536,536,180.60,1
3348,3348,E18281,1,7.714286,12,54,5,1,439,439,80.82,1
3349,3349,E18282,1,8.583333,48,103,9,2,385,266,178.05,1
3350,3350,E18283,1,1.816456,13,861,63,11,596,262,1294.83,3
3351,3351,E18287,4,15.285714,48,428,18,1,460,460,678.28,1

In [180]:
df.drop(['Unnamed: 0'],axis=1, inplace =True)

In [181]:
df

,customer_id,min_basket,avg_basket,max_basket,tot_basket,num_basket,num_invoice,first_buy,last_buy,tot_sales,k_value
0,E12747,1,12.714286,48,979,24,8,582,261,3177.01,3
1,E12748,1,4.737705,48,10982,281,128,597,259,16546.71,2
2,E12749,1,7.421687,48,1232,57,4,472,262,3486.79,3
3,E12820,4,12.918919,48,478,17,3,585,262,598.58,1
4,E12821,2,11.666667,24,70,4,1,473,473,92.72,1
...,...,...,...,...,...,...,...,...,...,...,...
3347,E18280,2,4.500000,8,45,9,1,536,536,180.60,1
3348,E18281,1,7.714286,12,54,5,1,439,439,80.82,1
3349,E18282,1,8.583333,48,103,9,2,385,266,178.05,1
3350,E18283,1,1.816456,13,861,63,11,596,262,1294.83,3
3351,E18287,4,15.285714,48,428,18,1,460,460,678.28,1

In [182]:
customer

,customer_id,city,state,pop_thousand,land_sq_meter,pop_size,city_type,city_lctn
0,E13313,Honolulu,HI,339,156,small,sightseeing,other
1,E18097,Houston,TX,2325,1658,middle,other,south
2,E16656,San Jose,CA,1003,461,middle,sightseeing,west
3,E16875,Phoenix,AZ,1759,1341,middle,other,west
4,E13094,Phoenix,AZ,1759,1341,middle,other,west
...,...,...,...,...,...,...,...,...
3453,E14698,Las Vegas,NV,675,367,small,sightseeing,west
3454,E13298,San Diego,CA,1429,844,middle,sightseeing,west
3455,E14569,New York,NY,8177,778,big,metro,east
3456,E16688,Phoenix,AZ,1759,1341,middle,other,west
3457,E12985,Los Angeles,CA,3985,1216,middle,metro,west

In [183]:
customer = customer[['customer_id','city']]

In [184]:
customer

     customer_id         city
0         E13313     Honolulu
1         E18097      Houston
2         E16656     San Jose
3         E16875      Phoenix
4         E13094      Phoenix
...          ...          ...
3453      E14698    Las Vegas
3454      E13298    San Diego
3455      E14569     New York
3456      E16688      Phoenix
3457      E12985  Los Angeles

[3458 rows x 2 columns]

In [185]:
df = pd.merge(df, customer, on=['customer_id'],how ='left')

In [186]:
df

,customer_id,min_basket,avg_basket,max_basket,tot_basket,num_basket,num_invoice,first_buy,last_buy,tot_sales,k_value,city
0,E12747,1,12.714286,48,979,24,8,582,261,3177.01,3,New York
1,E12748,1,4.737705,48,10982,281,128,597,259,16546.71,2,Phoenix
2,E12749,1,7.421687,48,1232,57,4,472,262,3486.79,3,Dallas
3,E12820,4,12.918919,48,478,17,3,585,262,598.58,1,Houston
4,E12821,2,11.666667,24,70,4,1,473,473,92.72,1,Honolulu
...,...,...,...,...,...,...,...,...,...,...,...,...
3347,E18280,2,4.500000,8,45,9,1,536,536,180.60,1,San Diego
3348,E18281,1,7.714286,12,54,5,1,439,439,80.82,1,New York
3349,E18282,1,8.583333,48,103,9,2,385,266,178.05,1,New York
3350,E18283,1,1.816456,13,861,63,11,596,262,1294.83,3,San Diego
3351,E18287,4,15.285714,48,428,18,1,460,460,678.28,1,San Antonio

In [155]:
cs= cs[['product_name','customer_id','category_1','category_2']]

In [156]:
cs= cs.drop_duplicates()

In [157]:
df = pd.merge(df, cs, on=['customer_id'],how ='left')

In [158]:
df

,customer_id,min_basket,avg_basket,max_basket,tot_basket,num_basket,num_invoice,first_buy,last_buy,tot_sales,k_value,city,product_name,category_1,category_2
0,E12747,1,12.714286,48,979,24,8,582,261,3177.01,3,New York,PAINTED METAL PEARS ASSORTED,Arts,Crafts & Sewing
1,E12747,1,12.714286,48,979,24,8,582,261,3177.01,3,New York,WOOD BLACK BOARD ANT WHITE FINISH,Presentation Supplies,Chalkboards
2,E12747,1,12.714286,48,979,24,8,582,261,3177.01,3,New York,WOODEN FRAME ANTIQUE WHITE,Picture Frames,Wall & Tabletop Picture Frames
3,E12747,1,12.714286,48,979,24,8,582,261,3177.01,3,New York,WOODEN PICTURE FRAME WHITE FINISH,Picture Frames,Wall & Tabletop Picture Frames
4,E12747,1,12.714286,48,979,24,8,582,261,3177.01,3,New York,HANGING JAM JAR T-LIGHT HOLDER,Candleholders,Tea Light Candle Holders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178901,E18287,4,15.285714,48,428,18,1,460,460,678.28,1,San Antonio,CERAMIC STRAWBERRY MONEY BOX,Novelty Toys & Amusements,Kids Money Banks
178902,E18287,4,15.285714,48,428,18,1,460,460,678.28,1,San Antonio,SET/4 RED MINI ROSE CANDLE IN BOWL,Home Décor Products,Jar Candles
178903,E18287,4,15.285714,48,428,18,1,460,460,678.28,1,San Antonio,S/4 PINK FLOWER CANDLES IN BOWL,Home Décor Products,Candles
178904,E18287,4,15.285714,48,428,18,1,460,460,678.28,1,San Antonio,S/4 IVORY MINI ROSE CANDLE IN BOWL,Home Décor Products,Candles
178905,E18287,4,15.285714,48,428,18,1,460,460,678.28,1,San Antonio,SET/6 PURPLE BUTTERFLY T-LIGHTS,Novelty Lighting,Flameless Candles

In [187]:
df= df.drop('customer_id',axis=1)
df

,min_basket,avg_basket,max_basket,tot_basket,num_basket,num_invoice,first_buy,last_buy,tot_sales,k_value,city
0,1,12.714286,48,979,24,8,582,261,3177.01,3,New York
1,1,4.737705,48,10982,281,128,597,259,16546.71,2,Phoenix
2,1,7.421687,48,1232,57,4,472,262,3486.79,3,Dallas
3,4,12.918919,48,478,17,3,585,262,598.58,1,Houston
4,2,11.666667,24,70,4,1,473,473,92.72,1,Honolulu
...,...,...,...,...,...,...,...,...,...,...,...
3347,2,4.500000,8,45,9,1,536,536,180.60,1,San Diego
3348,1,7.714286,12,54,5,1,439,439,80.82,1,New York
3349,1,8.583333,48,103,9,2,385,266,178.05,1,New York
3350,1,1.816456,13,861,63,11,596,262,1294.83,3,San Diego
3351,4,15.285714,48,428,18,1,460,460,678.28,1,San Antonio

In [188]:
df_raw_x = df.drop('k_value',axis =1)

In [189]:
df_raw_y = df[['k_value']]

In [190]:
df_raw_dummy = pd.get_dummies(df_raw_x)
df_raw_dummy

,min_basket,avg_basket,max_basket,tot_basket,num_basket,num_invoice,first_buy,last_buy,tot_sales,city_Chicago,...,city_Houston,city_Las Vegas,city_Los Angeles,city_Miami,city_New York,city_Philadelphia,city_Phoenix,city_San Antonio,city_San Diego,city_San Jose
0,1,12.714286,48,979,24,8,582,261,3177.01,0,...,0,0,0,0,1,0,0,0,0,0
1,1,4.737705,48,10982,281,128,597,259,16546.71,0,...,0,0,0,0,0,0,1,0,0,0
2,1,7.421687,48,1232,57,4,472,262,3486.79,0,...,0,0,0,0,0,0,0,0,0,0
3,4,12.918919,48,478,17,3,585,262,598.58,0,...,1,0,0,0,0,0,0,0,0,0
4,2,11.666667,24,70,4,1,473,473,92.72,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3347,2,4.500000,8,45,9,1,536,536,180.60,0,...,0,0,0,0,0,0,0,0,1,0
3348,1,7.714286,12,54,5,1,439,439,80.82,0,...,0,0,0,0,1,0,0,0,0,0
3349,1,8.583333,48,103,9,2,385,266,178.05,0,...,0,0,0,0,1,0,0,0,0,0
3350,1,1.816456,13,861,63,11,596,262,1294.83,0,...,0,0,0,0,0,0,0,0,1,0
3351,4,15.285714,48,428,18,1,460,460,678.28,0,...,0,0,0,0,0,0,0,1,0,0

# 로지스틱

In [163]:
# 로지스틱 회귀
from statsmodels.api import Logit

In [31]:
df_train, df_test = train_test_split(df, # 데이터
                                     test_size = 0.3, # test 데이터의 비율
                                     random_state = 1234)  # random state

print("train data size : {}".format(df_train.shape))
print("test data size : {}".format(df_test.shape))

train data size : (2346, 11)
test data size : (1006, 11)

In [ ]:
log_model = Logit.from_formula("""SCALE ~ PT_WIDTH+PT_LENGTH+PT_WEIGHT+C(FUR_NO)+C(FUR_NO_ROW)+\
FUR_HZ_TEMP+FUR_HZ_TIME+FUR_SZ_TEMP+FUR_SZ_TIME+FUR_TIME+FUR_EXTEMP+ROLLING_TEMP_T5+C(HSB)+ROLLING_DESCALING+C(WORK_GR)+FUR_HZ_X+FUR_SZ_X""", df_train)
# 적합
log_result = log_model.fit()

# 결과 출력
print(log_result.summary())

# 랜덤포레스트

In [191]:
#분류 Random Forest
from sklearn.ensemble import RandomForestClassifier

In [192]:
# train_test_split(X: 설명변수 데이터, Y: 목표변수 데이터, test_size = test 데이터 비율, random_state: 랜덤)
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(df_raw_dummy, # 설명변수 데이터
                                                                df_raw_y, # 목표변수 데이터
                                                                test_size = 0.3, # test 데이터의 비율
                                                                random_state = 1234)  # random state

print("train data X size : {}".format(df_train_x.shape))
print("train data Y size : {}".format(df_train_y.shape))
print("test data X size : {}".format(df_test_x.shape))
print("test data Y size : {}".format(df_test_y.shape))

train data X size : (2346, 22)
train data Y size : (2346, 1)
test data X size : (1006, 22)
test data Y size : (1006, 1)

In [195]:
rf_uncustomized = RandomForestClassifier(random_state=1234)
rf_uncustomized.fit(df_train_x, df_train_y)

print("Accuracy on training set: {:.3f}".format(rf_uncustomized.score(df_train_x, df_train_y)))
print("Accuracy on test set: {:.3f}".format(rf_uncustomized.score(df_test_x, df_test_y)))
#test set 성능도 잘나온다. 모델의 복작도를 줄이고, test성능을 최대한 높이고자 모델링을 해보자!
print(df_train_x.shape)
print(df_train_y.shape)
y_pred = rf_uncustomized.predict(df_test_x)

# train 데이터 셋 정확도
print("Accucary on training set: {:.3f}".format(rf_uncustomized.score(df_train_x, df_train_y)))
# test 데이터 셋 정확도
print("Accuracy on test set: {:.3f}\n".format(rf_uncustomized.score(df_test_x, df_test_y)))
# confusion matrix
print("Confusion matrix: \n{}".format(confusion_matrix(df_test_y, y_pred)))

# 목표변수의 빈도 불균형 : f1 score로 모델 평가 
print(classification_report(df_test_y, y_pred, digits=3))

C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\2116634173.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_uncustomized.fit(df_train_x, df_train_y)

Accuracy on training set: 1.000
Accuracy on test set: 0.983
(2346, 22)
(2346, 1)
Accucary on training set: 1.000
Accuracy on test set: 0.983

Confusion matrix:
[[ 43   6   0   0]
 [  0 783   0   6]
 [  0   0   5   2]
 [  0   3   0 158]]
              precision    recall  f1-score   support

           0      1.000     0.878     0.935        49
           1      0.989     0.992     0.991       789
           2      1.000     0.714     0.833         7
           3      0.952     0.981     0.966       161

    accuracy                          0.983      1006
   macro avg      0.985     0.891     0.931      1006
weighted avg      0.983     0.983     0.983      1006

In [175]:
from sklearn import datasets

import joblib

In [176]:
joblib.dump(rf_final, './rf_final.pkl')

['./rf_final.pkl']

In [193]:
# 트리의 개수, 트리의 깊이, 잎사귀노드의 최소 자료수, 분리노드의 최소 샘플수 순서로 모델링 시작!

train_accuracy = []; test_accuracy = []
para_n_tree = [n_tree * 10 for n_tree in range(1, 16)]

for v_n_estimators in para_n_tree:
    rf = RandomForestClassifier(n_estimators = v_n_estimators, random_state = 1234)
    rf.fit(df_train_x, df_train_y)
    train_accuracy.append(rf.score(df_train_x, df_train_y))
    test_accuracy.append(rf.score(df_test_x, df_test_y))

df_accuracy_n = pd.DataFrame()
df_accuracy_n["n_estimators"] = para_n_tree
df_accuracy_n["TrainAccuracy"] = train_accuracy
df_accuracy_n["TestAccuracy"] = test_accuracy

df_accuracy_n.round(3)

C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\1335333031.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)

    n_estimators  TrainAccuracy  TestAccuracy
0             10            1.0         0.981
1             20            1.0         0.980
2             30            1.0         0.981
3             40            1.0         0.978
4             50            1.0         0.982
5             60            1.0         0.982
6             70            1.0         0.982
7             80            1.0         0.982
8             90            1.0         0.982
9            100            1.0         0.983
10           110            1.0         0.983
11           120            1.0         0.981
12           130            1.0         0.982
13           140            1.0         0.982
14           150            1.0         0.982

In [38]:
#최대 깊이 변경에 따른 정확도 변화

train_accuracy = []; test_accuracy = []
# max_depth: 최대 깊이 변경
para_depth = [depth for depth in range(1, 17)]

for v_max_depth in para_depth:
    rf = RandomForestClassifier(max_depth = v_max_depth, n_estimators = 100, random_state=1234)
    rf.fit(df_train_x, df_train_y)
    train_accuracy.append(rf.score(df_train_x, df_train_y))
    test_accuracy.append(rf.score(df_test_x, df_test_y))

# 데이터 테이블로 저장
df_accuracy_depth = pd.DataFrame()
df_accuracy_depth["Depth"] = para_depth
df_accuracy_depth["TrainAccuracy"] = train_accuracy
df_accuracy_depth["TestAccuracy"] = test_accuracy

# 테이블 결과
df_accuracy_depth.round(3)

C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\611562224.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)

    Depth  TrainAccuracy  TestAccuracy
0       1          0.877         0.884
1       2          0.919         0.922
2       3          0.950         0.949
3       4          0.966         0.965
4       5          0.983         0.977
5       6          0.991         0.978
6       7          0.994         0.979
7       8          0.996         0.978
8       9          0.998         0.979
9      10          0.999         0.980
10     11          1.000         0.982
11     12          1.000         0.980
12     13          1.000         0.982
13     14          1.000         0.982
14     15          1.000         0.982
15     16          1.000         0.982

In [39]:
train_accuracy = []; test_accuracy = []

para_leaf = [n_leaf * 2 for n_leaf in range(1, 11)]

for v_min_samples_leaf in para_leaf:
    rf = RandomForestClassifier(min_samples_leaf = v_min_samples_leaf,
                                max_depth = 11, n_estimators = 100, random_state=1234)
    rf.fit(df_train_x, df_train_y)
    train_accuracy.append(rf.score(df_train_x, df_train_y))
    test_accuracy.append(rf.score(df_test_x, df_test_y))

df_accuracy_leaf = pd.DataFrame()
df_accuracy_leaf["MinSamplesLeaf"] = para_leaf
df_accuracy_leaf["TrainAccuracy"] = train_accuracy
df_accuracy_leaf["TestAccuracy"] = test_accuracy

df_accuracy_leaf.round(3)

C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\4260718895.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\4260718895.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\4260718895.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\4260718895.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\4260718895.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\4260718895.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\4260718895.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\4260718895.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\4260718895.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)
C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\4260718895.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(df_train_x, df_train_y)

   MinSamplesLeaf  TrainAccuracy  TestAccuracy
0               2          0.997         0.981
1               4          0.993         0.978
2               6          0.991         0.977
3               8          0.985         0.972
4              10          0.983         0.973
5              12          0.983         0.974
6              14          0.982         0.974
7              16          0.979         0.975
8              18          0.980         0.974
9              20          0.978         0.974

# GB

In [167]:
# 분류 Gradient Boosting
from sklearn.ensemble import GradientBoostingClassifier

In [168]:
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(df_raw_dummy, # 설명변수 데이터
                                                                df_raw_y, # 목표변수 데이터
                                                                test_size = 0.3, # test 데이터의 비율
                                                                random_state = 1234)

In [169]:
# 그래디언트 부스팅 모델 생성: GradientBoostingClassifier
gb_uncustomized = GradientBoostingClassifier(random_state=1234)
gb_uncustomized.fit(df_train_x, df_train_y)
# train 데이터 셋 정확도
print("Accuracy on train set: {:.3f}".format(gb_uncustomized.score (df_train_x, df_train_y)))
# test 데이터 셋 정확도
print("Accuracy on test set: {:.3f}".format(gb_uncustomized.score (df_test_x, df_test_y)))

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

KeyboardInterrupt:

In [43]:
# train 및 test 정확도 결과 저장용
train_accuracy = []; test_accuracy = []
# n_estimatos: 트리 수 변경: 10~150
para_n_tree = [n_tree * 10 for n_tree in range(1, 18)]

for v_n_estimators in para_n_tree:
    gb = GradientBoostingClassifier(n_estimators = v_n_estimators, random_state = 1234)
    gb.fit(df_train_x, df_train_y)
    train_accuracy.append(gb.score(df_train_x, df_train_y))
    test_accuracy.append(gb.score(df_test_x, df_test_y))

# 데이터 테이블로 저장
df_accuracy_n = pd.DataFrame()
df_accuracy_n["Estimators"] = para_n_tree
df_accuracy_n["TrainAccuracy"] = train_accuracy
df_accuracy_n["TestAccuracy"] = test_accuracy

# n_estimators별 정확도 테이블
df_accuracy_n.round(3)

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

    Estimators  TrainAccuracy  TestAccuracy
0           10          0.983         0.973
1           20          0.995         0.983
2           30          0.999         0.984
3           40          0.999         0.985
4           50          1.000         0.986
5           60          1.000         0.986
6           70          1.000         0.986
7           80          1.000         0.986
8           90          1.000         0.987
9          100          1.000         0.988
10         110          1.000         0.988
11         120          1.000         0.988
12         130          1.000         0.988
13         140          1.000         0.988
14         150          1.000         0.988
15         160          1.000         0.988
16         170          1.000         0.989

In [44]:
train_accuracy = []; test_accuracy = []
# learning_rate 학습률 변경: 0.1 ~ 0.9
para_lr = [lr * 0.1 for lr in range(1, 10)]

for v_learning_rate in para_lr:
    gb = GradientBoostingClassifier(learning_rate = v_learning_rate, n_estimators = 170, random_state = 1234)
    gb.fit(df_train_x, df_train_y)
    train_accuracy.append(gb.score(df_train_x, df_train_y))
    test_accuracy.append(gb.score(df_test_x, df_test_y))

# 데이터 테이블로 저장
df_accuracy_lr = pd.DataFrame()
df_accuracy_lr["LearningRate"] = para_lr
df_accuracy_lr["TrainAccuracy"] = train_accuracy
df_accuracy_lr["TestAccuracy"] = test_accuracy

# LearningRate별 정확도 테이블
df_accuracy_lr.round(3)

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

   LearningRate  TrainAccuracy  TestAccuracy
0           0.1          1.000         0.989
1           0.2          1.000         0.986
2           0.3          1.000         0.989
3           0.4          1.000         0.988
4           0.5          1.000         0.987
5           0.6          1.000         0.987
6           0.7          1.000         0.984
7           0.8          1.000         0.988
8           0.9          0.994         0.982

In [45]:
# train 및 test 정확도 결과 저장용
train_accuracy = []; test_accuracy = []
# max_depth: 최대 깊이 변경
para_depth = [depth for depth in range(1, 11)]

for v_max_depth in para_depth:
    gb = GradientBoostingClassifier(max_depth = v_max_depth,
                                    n_estimators = 170, learning_rate = 0.1,random_state=1234)
    gb.fit(df_train_x, df_train_y)
    train_accuracy.append(gb.score(df_train_x, df_train_y))
    test_accuracy.append(gb.score(df_test_x, df_test_y))

# 데이터 테이블로 저장
df_accuracy_depth = pd.DataFrame()
df_accuracy_depth["Depth"] = para_depth
df_accuracy_depth["TrainAccuracy"] = train_accuracy
df_accuracy_depth["TestAccuracy"] = test_accuracy

# max_depth별 정확도 테이블
df_accuracy_depth.round(3)

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

   Depth  TrainAccuracy  TestAccuracy
0      1          0.995         0.983
1      2          1.000         0.990
2      3          1.000         0.989
3      4          1.000         0.985
4      5          1.000         0.987
5      6          1.000         0.985
6      7          1.000         0.986
7      8          1.000         0.979
8      9          1.000         0.975
9     10          1.000         0.977

In [47]:
# train 및 test 정확도 결과 저장용
train_accuracy = []; test_accuracy = []
# min_samples_leaf: 잎사귀 수 제한
para_leaf = [n_leaf * 4 for n_leaf in range(1, 11)]

for v_min_samples_leaf in para_leaf:
    gb = GradientBoostingClassifier(min_samples_leaf = v_min_samples_leaf,
                                     max_depth = 2, n_estimators = 170, learning_rate = 0.1, random_state=1234)
    gb.fit(df_train_x, df_train_y)
    train_accuracy.append(gb.score(df_train_x, df_train_y))
    test_accuracy.append(gb.score(df_test_x, df_test_y))

# 데이터 테이블로 저장
df_accuracy_leaf = pd.DataFrame()
df_accuracy_leaf["MinSamplesLeaf"] = para_leaf
df_accuracy_leaf["TrainAccuracy"] = train_accuracy
df_accuracy_leaf["TestAccuracy"] = test_accuracy

# min_samples_leaf별 정확도 테이블
df_accuracy_leaf.round(3)

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

   MinSamplesLeaf  TrainAccuracy  TestAccuracy
0               4          1.000         0.988
1               8          0.997         0.984
2              12          0.998         0.987
3              16          1.000         0.989
4              20          1.000         0.985
5              24          1.000         0.985
6              28          1.000         0.982
7              32          1.000         0.983
8              36          1.000         0.983
9              40          1.000         0.980

In [48]:
# train 및 test 정확도 결과 저장용
train_accuracy = []; test_accuracy = []
# min_samples_split: 분할하기 위한 노드의 최소 샘플 수 
para_split = [n_split * 10 for n_split in range(2, 11)]

for v_min_samples_split in para_split:
    gb = GradientBoostingClassifier(min_samples_split = v_min_samples_split, min_samples_leaf = 2,
                                    max_depth = 2,n_estimators = 170, learning_rate = 0.1, random_state=1234)
    gb.fit(df_train_x, df_train_y)
    train_accuracy.append(gb.score(df_train_x, df_train_y))
    test_accuracy.append(gb.score(df_test_x, df_test_y))

# 데이터 테이블로 저장
df_accuracy_split = pd.DataFrame()
df_accuracy_split["MinSamplesSplit"] = para_split
df_accuracy_split["TrainAccuracy"] = train_accuracy
df_accuracy_split["TestAccuracy"] = test_accuracy

# min_samples_leaf별 정확도 테이블
df_accuracy_split.round(3)

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

   MinSamplesSplit  TrainAccuracy  TestAccuracy
0               20            1.0         0.987
1               30            1.0         0.987
2               40            1.0         0.987
3               50            1.0         0.987
4               60            1.0         0.987
5               70            1.0         0.987
6               80            1.0         0.987
7               90            1.0         0.987
8              100            1.0         0.986

In [49]:
# 최종 모델
gb_final = GradientBoostingClassifier(min_samples_leaf = 2,min_samples_split=20, max_depth = 2, n_estimators = 170,
                                      learning_rate = 0.1, random_state=1234)
gb_final.fit(df_train_x, df_train_y)
# 예측
y_pred = gb_final.predict(df_test_x)

# train 데이터 셋 정확도
print("Accuracy on training set: {:.3f}".format(gb_final.score(df_train_x, df_train_y)))
# test 데이터 셋 정확도
print("Accuracy on test set: {:.3f}\n".format(gb_final.score(df_test_x, df_test_y)))
# confusion matrix
print("Confusion matrix: \n{}".format(confusion_matrix(df_test_y, y_pred)))

# 목표변수의 빈도 불균형 : f1 score로 모델 평가 
print(classification_report(df_test_y, y_pred, digits=3))

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy on training set: 1.000
Accuracy on test set: 0.987

Confusion matrix:
[[ 47   2   0   0]
 [  0 785   0   4]
 [  0   0   5   2]
 [  0   4   1 156]]
              precision    recall  f1-score   support

           0      1.000     0.959     0.979        49
           1      0.992     0.995     0.994       789
           2      0.833     0.714     0.769         7
           3      0.963     0.969     0.966       161

    accuracy                          0.987      1006
   macro avg      0.947     0.909     0.927      1006
weighted avg      0.987     0.987     0.987      1006

# SVM

In [170]:
# 분류 SVM
from sklearn.svm import SVC

In [171]:
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(df_raw_dummy, # 설명변수 데이터
                                                                df_raw_y, # 목표변수 데이터
                                                                test_size = 0.3, # test 데이터의 비율
                                                                random_state = 1234)

In [52]:
svm_uncustomized = SVC(random_state=1234)
svm_uncustomized.fit(df_train_x, df_train_y)
# train 데이터 셋 정확도
print("Accuracy on train set: {:.3f}".format(svm_uncustomized.score(df_train_x, df_train_y)))
# test 데이터 셋 정확도
print("Accuracy on test set: {:.3f}".format(svm_uncustomized.score(df_test_x, df_test_y)))
y_pred = svm_uncustomized.predict(df_test_x)
# confusion matrix
print("Confusion matrix: \n{}".format(confusion_matrix(df_test_y, y_pred)))

print(classification_report(df_test_y, y_pred, digits=3))

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy on train set: 0.918
Accuracy on test set: 0.927
Confusion matrix:
[[  0  48   0   1]
 [  0 777   0  12]
 [  0   0   7   0]
 [  0  12   0 149]]
              precision    recall  f1-score   support

           0      0.000     0.000     0.000        49
           1      0.928     0.985     0.956       789
           2      1.000     1.000     1.000         7
           3      0.920     0.925     0.923       161

    accuracy                          0.927      1006
   macro avg      0.712     0.728     0.720      1006
weighted avg      0.882     0.927     0.904      1006

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [172]:
v_feature_name = df_raw_dummy.columns
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_raw_dummy)
df_scaled = pd.DataFrame(df_scaled, columns=v_feature_name)
df_scaled

MemoryError: Unable to allocate 6.59 GiB for an array with shape (178906, 4946) and data type float64

In [56]:
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(df_scaled, # 설명변수 데이터
                                                                df_raw_y, # 목표변수 데이터
                                                                test_size = 0.3, # test 데이터의 비율
                                                                random_state = 1234)

In [57]:
svm_scaled = SVC(random_state=1234)
svm_scaled.fit(df_train_x, df_train_y)
# train 데이터 셋 정확도
print("Accuracy on training set: {:.3f}".format(svm_scaled.score(df_train_x, df_train_y)))
# test 데이터 셋 정확도
print("Accuracy on test set: {:.3f}".format(svm_scaled.score(df_test_x, df_test_y)))

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy on training set: 0.984
Accuracy on test set: 0.978

In [58]:
# train 및 test 정확도 결과 저장용
train_accuracy = []; test_accuracy = []
# c: 규제(0.01, 0.1, 1, 10)
para_c = [10 ** c for c in range(-2, 2)]

for v_C in para_c:
    svm = SVC(C = v_C, random_state = 1234)
    svm.fit(df_train_x, df_train_y)
    train_accuracy.append(svm.score(df_train_x, df_train_y))
    test_accuracy.append(svm.score(df_test_x, df_test_y))

# 데이터 테이블로 저장
df_accuracy_c = pd.DataFrame()
df_accuracy_c["C"] = para_c
df_accuracy_c["TrainAccuracy"] = train_accuracy
df_accuracy_c["TestAccuracy"] = test_accuracy

# C별 정확도 테이블 
df_accuracy_c.round(3)

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

       C  TrainAccuracy  TestAccuracy
0   0.01          0.791         0.784
1   0.10          0.918         0.909
2   1.00          0.984         0.978
3  10.00          0.997         0.986

In [59]:
# train 및 test 정확도 결과 저장용
train_accuracy = []; test_accuracy = []
# gamma: 규제(0.01, 0.1, 1, 10)
para_gamma = [10 **gamma for gamma in range(-2, 2)]

for v_gamma in para_gamma:
    svm = SVC(gamma = v_gamma, C = 10, random_state = 1234)
    svm.fit(df_train_x, df_train_y)
    train_accuracy.append(svm.score(df_train_x, df_train_y))
    test_accuracy.append(svm.score(df_test_x, df_test_y))

# 데이터 테이블로 저장
df_accuracy_gamma = pd.DataFrame()
df_accuracy_gamma["gamma"] = para_gamma
df_accuracy_gamma["TrainAccuracy"] = train_accuracy
df_accuracy_gamma["TestAccuracy"] = test_accuracy

# Gamma별 정확도 테이블 
df_accuracy_gamma.round(3)

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

   gamma  TrainAccuracy  TestAccuracy
0   0.01          0.994         0.993
1   0.10          0.999         0.979
2   1.00          1.000         0.879
3  10.00          1.000         0.787

In [60]:
# 최종 모델
svc_final = SVC(gamma = 0.01, C = 10, random_state=1234)
svc_final.fit(df_train_x, df_train_y)
# 평가
y_pred = svc_final.predict(df_test_x)

# train 데이터 셋 정확도
print("Accucary on training set: {:.3f}".format(svc_final.score(df_train_x, df_train_y)))
# test 데이터 셋 정확도
print("Accuracy on test set: {:.3f}\n".format(svc_final.score(df_test_x, df_test_y)))
# confusion matrix
print("Confusion matrix: \n{}".format(confusion_matrix(df_test_y, y_pred)))

# 목표변수의 빈도 불균형 : f1 score로 모델 평가 
print(classification_report(df_test_y, y_pred, digits=3))

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accucary on training set: 0.994
Accuracy on test set: 0.993

Confusion matrix:
[[ 47   2   0   0]
 [  1 787   0   1]
 [  0   0   7   0]
 [  0   2   1 158]]
              precision    recall  f1-score   support

           0      0.979     0.959     0.969        49
           1      0.995     0.997     0.996       789
           2      0.875     1.000     0.933         7
           3      0.994     0.981     0.987       161

    accuracy                          0.993      1006
   macro avg      0.961     0.985     0.972      1006
weighted avg      0.993     0.993     0.993      1006

In [61]:
# 분류 NN (MLPClassifier)
from sklearn.neural_network import MLPClassifier

In [62]:
df_train_x, df_test_x, df_train_y, df_test_y= train_test_split(df_raw_dummy, df_raw_y, test_size = 0.4,random_state = 1234)
print("train data X size : {}".format(df_train_x.shape))
print("test data X size : {}".format(df_test_x.shape))
print("train data Y size : {}".format(df_train_y.shape))
print("test data Y size : {}".format(df_test_y.shape))

train data X size : (2011, 22)
test data X size : (1341, 22)
train data Y size : (2011, 1)
test data Y size : (1341, 1)

In [63]:
nn_uncustomized = MLPClassifier(random_state=1234)
nn_uncustomized.fit(df_train_x, df_train_y)

exy_pred = nn_uncustomized.predict(df_test_x)
# train 데이터 셋 정확도
print("Accuracy on training set: {:.3f}".format(nn_uncustomized.score(df_train_x, df_train_y)))
# test 데이터 셋 정확도
print("Accuracy on test set: {:.3f}".format(nn_uncustomized.score(df_test_x, df_test_y)))

print("Confusion matrix: \n{}".format(confusion_matrix(df_test_y, exy_pred)))

# 목표변수의 빈도 불균형 : f1 score로 모델 평가 
print(classification_report(df_test_y, exy_pred, digits=3))

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy on training set: 0.924
Accuracy on test set: 0.937
Confusion matrix:
[[  19   42    0    0]
 [   0 1050    0   11]
 [   0    0    8    0]
 [   0   20   11  180]]
              precision    recall  f1-score   support

           0      1.000     0.311     0.475        61
           1      0.944     0.990     0.966      1061
           2      0.421     1.000     0.593         8
           3      0.942     0.853     0.896       211

    accuracy                          0.937      1341
   macro avg      0.827     0.789     0.732      1341
weighted avg      0.943     0.937     0.931      1341

In [64]:
# train 및 test 정확도 결과 저장용
train_accuracy = []; test_accuracy = []
# hidden_layer_sizes: 은닉층 변경 (20~240, by 30)
para_hidden = [20 * hidden for hidden in range(1, 11)]

for v_hidden in para_hidden:
#     nn = MLPClassifier(hidden_layer_sizes = v_hidden, random_state = 1234)
    nn = MLPClassifier(hidden_layer_sizes = (v_hidden,v_hidden), random_state = 1234)    
    nn.fit(df_train_x, df_train_y)
    train_accuracy.append(nn.score(df_train_x, df_train_y))
    test_accuracy.append(nn.score(df_test_x, df_test_y))

# 데이터 테이블로 저장
df_accuracy_hidden = pd.DataFrame()
df_accuracy_hidden["HiddenLayer"] = para_hidden
df_accuracy_hidden["TrainAccuracy"] = train_accuracy
df_accuracy_hidden["TestAccuracy"] = test_accuracy

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [65]:
# 은닉층별 정확도 테이블 
df_accuracy_hidden.round(3)

   HiddenLayer  TrainAccuracy  TestAccuracy
0           20          0.937         0.936
1           40          0.942         0.947
2           60          0.907         0.894
3           80          0.924         0.927
4          100          0.912         0.916
5          120          0.932         0.937
6          140          0.935         0.943
7          160          0.854         0.849
8          180          0.929         0.927
9          200          0.918         0.922

In [66]:
# 은닉층 지정(임의)
hidden_layer_sizes = 40

In [67]:
# train 및 test 정확도 결과 저장용
train_accuracy = []; test_accuracy = []
# activation 변경 
para_function = ["logistic", "tanh", "relu"]

for v_function in para_function:
    nn = MLPClassifier(activation = v_function, hidden_layer_sizes = (40,40), random_state = 1234)
    nn.fit(df_train_x, df_train_y)
    train_accuracy.append(nn.score(df_train_x, df_train_y))
    test_accuracy.append(nn.score(df_test_x, df_test_y))

# 데이터 테이블로 저장
df_accuracy_function = pd.DataFrame()
df_accuracy_function["ActivationFunction"] = para_function
df_accuracy_function["TrainAccuracy"] = train_accuracy
df_accuracy_function["TestAccuracy"] = test_accuracy

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [68]:
# Activation Function별 정확도 테이블 
df_accuracy_function.round(3)

  ActivationFunction  TrainAccuracy  TestAccuracy
0           logistic          0.951         0.958
1               tanh          0.907         0.919
2               relu          0.942         0.947

In [69]:
# Activation Function 지정(임의)
activation = "logistic"

In [70]:
# train 및 test 정확도 결과 저장용
train_accuracy = []; test_accuracy = []
# solver 변경 
para_solver = ["lbfgs", "sgd", "adam"]

for v_solver in para_solver:
    nn = MLPClassifier(solver = v_solver, activation = "logistic", hidden_layer_sizes = (40,40), random_state = 1234)
    nn.fit(df_train_x, df_train_y)
    train_accuracy.append(nn.score(df_train_x, df_train_y))
    test_accuracy.append(nn.score(df_test_x, df_test_y))

# 데이터 테이블로 저장
df_accuracy_solver = pd.DataFrame()
df_accuracy_solver["Solver"] = para_solver
df_accuracy_solver["TrainAccuracy"] = train_accuracy
df_accuracy_solver["TestAccuracy"] = test_accuracy

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:559: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [71]:
df_accuracy_solver.round(3)

  Solver  TrainAccuracy  TestAccuracy
0  lbfgs          0.916         0.919
1    sgd          0.901         0.916
2   adam          0.951         0.958

In [72]:
# Solver 지정(임의)
solver = "adam"

In [74]:
print("데이터 크기: ", df_train_x.shape)

# train 및 test 정확도 결과 저장용
train_accuracy = []; test_accuracy = []

# Mini Batch 변경 :
para_batch = [10 * batch for batch in range(1, 12)]

print(para_batch)

데이터 크기:  (2011, 22)
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110]

In [75]:
for v_batch in para_batch:
    nn = MLPClassifier(batch_size = v_batch, solver = "adam", activation = "logistic",
                       hidden_layer_sizes = (40,40), random_state = 1234)
    nn.fit(df_train_x, df_train_y)
    train_accuracy.append(nn.score(df_train_x, df_train_y))
    test_accuracy.append(nn.score(df_test_x, df_test_y))

# 데이터 테이블로 저장
df_accuracy_batch = pd.DataFrame()
df_accuracy_batch["Mini Batch"] = para_batch
df_accuracy_batch["TrainAccuracy"] = train_accuracy
df_accuracy_batch["TestAccuracy"] = test_accuracy

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [76]:
# Mini Batch Size별 정확도 테이블
df_accuracy_batch.round(3)

    Mini Batch  TrainAccuracy  TestAccuracy
0           10          0.952         0.953
1           20          0.943         0.941
2           30          0.941         0.946
3           40          0.955         0.958
4           50          0.947         0.957
5           60          0.951         0.954
6           70          0.949         0.959
7           80          0.949         0.951
8           90          0.960         0.959
9          100          0.949         0.958
10         110          0.953         0.957

In [ ]:
mini_batch_size = 90

In [77]:
nn_final = MLPClassifier(hidden_layer_sizes = (40, 40), activation = "logistic", solver = "adam",
                         batch_size = 90, random_state = 1234)
nn_final.fit(df_train_x, df_train_y)

# 평가
y_pred = nn_final.predict(df_test_x)

# train 데이터 셋 정확도
print("Accucary on training set: {:.3f}".format(nn_final.score(df_train_x, df_train_y)))
# test 데이터 셋 정확도
print("Accuracy on test set: {:.3f}\n".format(nn_final.score(df_test_x, df_test_y)))
# confusion matrix
print("Confusion matrix: \n{}".format(confusion_matrix(df_test_y, y_pred)))

# 목표변수의 빈도 불균형 : f1 score로 모델 평가 
print(classification_report(df_test_y, y_pred, digits=3))

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accucary on training set: 0.960
Accuracy on test set: 0.959

Confusion matrix:
[[  53    8    0    0]
 [   8 1039    0   14]
 [   0    0    0    8]
 [   1   16    0  194]]
              precision    recall  f1-score   support

           0      0.855     0.869     0.862        61
           1      0.977     0.979     0.978      1061
           2      0.000     0.000     0.000         8
           3      0.898     0.919     0.909       211

    accuracy                          0.959      1341
   macro avg      0.683     0.692     0.687      1341
weighted avg      0.954     0.959     0.956      1341

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\pyund\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [78]:
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

In [80]:
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(df_raw_dummy, # 설명변수 데이터
                                                                df_raw_y, # 목표변수 데이터
                                                                test_size = 0.3, # test 데이터의 비율
                                                                random_state = 1234)

In [81]:
# train 및 test 정확도 결과 저장용
train_accuracy = []; test_accuracy = []

para_n_neighbors = [i for i in range(3, 31)]

for v_n_neighbors in para_n_neighbors:
    knn = KNeighborsClassifier(n_neighbors = v_n_neighbors)
    knn.fit(df_train_x, df_train_y)
    train_accuracy.append(knn.score(df_train_x, df_train_y))
    test_accuracy.append(knn.score(df_test_x, df_test_y))

# 데이터 테이블로 저장
df_accuracy_neighbors = pd.DataFrame()
df_accuracy_neighbors["Neighbors"] = para_n_neighbors
df_accuracy_neighbors["TrainAccuracy"] = train_accuracy
df_accuracy_neighbors["TestAccuracy"] = test_accuracy
df_accuracy_neighbors.round(3)

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

AttributeError: 'NoneType' object has no attribute 'split'

In [87]:
# 분류 Decision Tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, roc_curve, auc

In [88]:
models = ["의사결정나무", "랜덤 포레스트", "그래디언트 부스팅","뉴럴넷"]
train_accuracy = []
test_accuracy = []
model_auc=[]
model_precision = []
model_recall=[]
model_f1_score=[]

In [89]:
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(df_raw_dummy, # 설명변수 데이터
                                                                df_raw_y, # 목표변수 데이터
                                                                test_size = 0.3, # test 데이터의 비율
                                                                random_state = 1234)  # random state

print("train data X size : {}".format(df_train_x.shape))
print("train data Y size : {}".format(df_train_y.shape))
print("test data X size : {}".format(df_test_x.shape))
print("test data Y size : {}".format(df_test_y.shape))

train data X size : (2346, 22)
train data Y size : (2346, 1)
test data X size : (1006, 22)
test data Y size : (1006, 1)

In [90]:
v_feature_name = df_raw_dummy.columns
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_raw_dummy)
df_scaled = pd.DataFrame(df_scaled, columns=v_feature_name)
df_scaled

,min_basket,avg_basket,max_basket,tot_basket,num_basket,num_invoice,first_buy,last_buy,tot_sales,city_Chicago,...,city_Houston,city_Las Vegas,city_Los Angeles,city_Miami,city_New York,city_Philadelphia,city_Phoenix,city_San Antonio,city_San Diego,city_San Jose
0,-0.374537,0.407747,1.199339,0.358138,-0.085647,0.815259,1.108251,-1.240679,1.024463,-0.335429,...,-0.295386,-0.1613,-0.416244,-0.130347,1.563655,-0.235405,-0.267603,-0.252565,-0.238914,-0.202469
1,-0.374537,-0.798688,1.199339,9.689944,10.835327,22.691840,1.265122,-1.262595,7.672467,-0.335429,...,-0.295386,-0.1613,-0.416244,-0.130347,-0.639527,-0.235405,3.736882,-0.252565,-0.238914,-0.202469
2,-0.374537,-0.392744,1.199339,0.594162,1.316657,0.086040,-0.042138,-1.229722,1.178499,-0.335429,...,-0.295386,-0.1613,-0.416244,-0.130347,-0.639527,-0.235405,-0.267603,-0.252565,-0.238914,-0.202469
3,0.309755,0.438697,1.199339,-0.109245,-0.383106,-0.096265,1.139625,-1.229722,-0.257646,-0.335429,...,3.385405,-0.1613,-0.416244,-0.130347,-0.639527,-0.235405,-0.267603,-0.252565,-0.238914,-0.202469
4,-0.146440,0.249297,-0.464272,-0.489868,-0.935529,-0.460874,-0.031680,1.082343,-0.509182,-0.335429,...,-0.295386,-0.1613,-0.416244,-0.130347,-0.639527,-0.235405,-0.267603,-0.252565,-0.238914,-0.202469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3347,-0.146440,-0.834640,-1.573345,-0.513191,-0.723058,-0.460874,0.627179,1.772675,-0.465484,-0.335429,...,-0.295386,-0.1613,-0.416244,-0.130347,-0.639527,-0.235405,-0.267603,-0.252565,4.185611,-0.202469
3348,-0.374537,-0.348489,-1.296077,-0.504795,-0.893035,-0.460874,-0.387255,0.709782,-0.515099,-0.335429,...,-0.295386,-0.1613,-0.416244,-0.130347,1.563655,-0.235405,-0.267603,-0.252565,-0.238914,-0.202469
3349,-0.374537,-0.217048,1.199339,-0.459083,-0.723058,-0.278570,-0.951991,-1.185891,-0.466752,-0.335429,...,-0.295386,-0.1613,-0.416244,-0.130347,1.563655,-0.235405,-0.267603,-0.252565,-0.238914,-0.202469
3350,-0.374537,-1.240519,-1.226760,0.248056,1.571621,1.362174,1.254664,-1.229722,0.088560,-0.335429,...,-0.295386,-0.1613,-0.416244,-0.130347,-0.639527,-0.235405,-0.267603,-0.252565,4.185611,-0.202469
3351,0.309755,0.796668,1.199339,-0.155890,-0.340612,-0.460874,-0.167635,0.939893,-0.218016,-0.335429,...,-0.295386,-0.1613,-0.416244,-0.130347,-0.639527,-0.235405,-0.267603,3.959371,-0.238914,-0.202469

In [91]:
df_train_x, df_test_x = train_test_split(df_scaled,test_size = 0.3, # test 데이터의 비율
                                                                random_state = 1234)  # random state

In [92]:

rf_final = RandomForestClassifier(random_state=1234)
rf_final.fit(df_train_x, df_train_y)
train_accuracy.append(rf_final.score(df_train_x,df_train_y))
test_accuracy.append(rf_final.score(df_test_x,df_test_y))
y_pred =rf_final.predict(df_test_x)
fpr,tpr,thresholds = roc_curve(df_test_y,y_pred)
roc_auc=auc(fpr,tpr)
model_auc.append(roc_auc)

C:\Users\pyund\AppData\Local\Temp\ipykernel_12348\4141279517.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_final.fit(df_train_x, df_train_y)

ValueError: multiclass format is not supported

In [94]:
gb_final = GradientBoostingClassifier(min_samples_leaf = 2,min_samples_split=20, max_depth = 2, n_estimators = 170,
                                      learning_rate = 0.1, random_state=1234)
gb_final.fit(df_train_x, df_train_y)
# 예측
y_pred = gb_final.predict(df_test_x)
train_accuracy.append(gb_final.score(df_train_x,df_train_y))
test_accuracy.append(gb_final.score(df_test_x,df_test_y))
fpr,tpr,thresholds = roc_curve(df_test_y,y_pred)
roc_auc=auc(fpr,tpr)
model_auc.append(roc_auc)

C:\Users\pyund\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

ValueError: multiclass format is not supported

In [ ]:
model_precision.append(precision_score(df_test_y,y_pred))
model_recall.append(recall_score(df_test_y,y_pred))
model_f1_score.append(f1_score(df_test_y,y_pred))

In [1]:
#B1편도훈